### ISSUE TITLE
Runtime Error: Type error while mapping data

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-worldstate-parser#171]
**Summary (short):**
Runtime Error
---
**Description:**
```log
 TypeError: Cannot read property 'map' of undefined
     at parseArray (~/warframe-status/node_modules/warframe-worldstate-parser/lib/WorldState.js:95:25)
     at new WorldState (~/warframe-status/node_modules/warframe-worldstate-parser/lib/WorldState.js:145:17)
     at JSONCache.parser (~/warframe-status/lib/utilities.js:69:10)
     at updating.httpGet.then (~/warframe-status/node_modules/json-fetch-cache/jsoncache.js:64:31)
     at process._tickCallback (internal/process/next_tick.js:68:7)
```

---
**If issue, Reproduction:** Parsing worldstate

---
**Evidence:**
See description

**Comment by TobiTenno** [comment]
closed with 40ddb89f11430ce1edcf249d1be0502978c224ff
